schema_version = "1.0.0"
id = "bfds"
version = "7.0.0-beta.4"
name = "BFDS fire simulations"
tagline = "Create and manage NIST FDS fire simulations"
maintainer = "Emanuele Gissi"
type = "add-on"
tags = ["Import-Export"]
website = "https://github.com/firetools/bfds"
blender_version_min = "4.5.0"
# blender_version_max = "4.5.9"
license = ["SPDX:GPL-3.0-or-later",]
copyright = [ "2025 Emanuele Gissi"]
# platforms = ["windows-x64", "windows-arm64", "macos-arm64", "macos-x64", "linux-x64"]
wheels = ["./wheels/f90nml-1.4.5-py2.py3-none-any.whl",]

[permissions]
files = "Import/export FDS files from/to disk"
network = "Display geographic positions, convert coordinates"
# clipboard = "Copy and paste bone transforms"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
  "*.blend1",
]
