schema_version = "1.0.0"
id = "bfds"
version = "7.0.0"
name = "NIST FDS fire simulations"
tagline = "BFDS, create and manage NIST FDS fire simulation cases"
maintainer = "Emanuele Gissi"
type = "add-on"
tags = ["Import-Export"]
website = "https://firetools.org/bfds"
blender_version_min = "4.5.0"
blender_version_max = "4.5.9"
license = ["SPDX:GPL-3.0-or-later",]
copyright = [ "2025 Emanuele Gissi"]
# platforms = ["windows-x64", "macos-arm64", "linux-x64"]

# # Optional: bundle 3rd party Python modules.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
# wheels = [
#   "./wheels/hexdump-3.3-py3-none-any.whl",
#   "./wheels/jsmin-3.0.1-py3-none-any.whl",
# ]

# # Optional: add-ons can list which resources they will require:
# # * files (for access of any filesystem operations)
# # * network (for internet access)
# # * clipboard (to read and/or write the system clipboard)
# # * camera (to capture photos and videos)
# # * microphone (to capture audio)
# #
# # If using network, remember to also check `bpy.app.online_access`
# # https://docs.blender.org/manual/en/dev/advanced/extensions/addons.html#internet-access
# #
# # For each permission it is important to also specify the reason why it is required.
# # Keep this a single short sentence without a period (.) at the end.
# # For longer explanations use the documentation or detail page.
#
[permissions]
files = "Import/export FDS files from/to disk"
# network = "Need to sync motion-capture data to server"
# clipboard = "Copy and paste bone transforms"

# # Optional: advanced build settings.
# # https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# # These are the default build excluded patterns.
# # You only need to edit them if you want different options.
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
